import * as Sentry from "https://esm.sh/@sentry/browser@8.55.0";

if (window.__CLAIMGUARD_WEB_SENTRY_READY__ !== true) {
  window.__CLAIMGUARD_WEB_SENTRY_READY__ = true;

  if (window.__CLAIMGUARD_WEB_DSN__) {
    Sentry.init({
      dsn: window.__CLAIMGUARD_WEB_DSN__,
      environment: window.__CLAIMGUARD_WEB_ENV__ || "development",
      tracesSampleRate: 0,
    });
  }
}

const app = document.getElementById("app");

function createNode(tagName, className, textContent) {
  const element = document.createElement(tagName);
  if (className) {
    element.className = className;
  }
  if (textContent) {
    element.textContent = textContent;
  }
  return element;
}

function renderLoading() {
  app.innerHTML = "";

  const hero = createNode("section", "hero fade-in");
  hero.append(
    createNode("p", "eyebrow", "ClaimGuard Network"),
    createNode("h1", "", "Network risk, surfaced."),
    createNode(
      "p",
      "lede",
      "This dashboard reads the synthetic detection report generated by the Phase 4 engine and highlights suspicious providers, members, and scheme-level summary metrics.",
    ),
    createNode("div", "status-row", "Loading detection report..."),
  );

  const grid = createNode("section", "grid fade-in");
  grid.append(createNode("div", "panel empty", "Waiting for the API proxy to return a report."));

  app.append(hero, grid);
}

function renderError(message) {
  app.innerHTML = "";

  const hero = createNode("section", "hero fade-in");
  hero.append(
    createNode("p", "eyebrow", "ClaimGuard Network"),
    createNode("h1", "", "Network risk, surfaced."),
    createNode(
      "p",
      "lede",
      "This dashboard reads the synthetic detection report generated by the Phase 4 engine and highlights suspicious providers, members, and scheme-level summary metrics.",
    ),
    createNode("div", "error", message),
  );

  app.append(hero);
}

function createMetric(label, value) {
  const metric = createNode("dl", "metric");
  metric.append(createNode("dt", "", label), createNode("dd", "", value));
  return metric;
}

function createKeyValuePanel(title, rows) {
  const panel = createNode("section", "panel");
  panel.append(createNode("h2", "", title));

  const metrics = createNode("div", "metrics");
  for (const row of rows) {
    metrics.append(createMetric(row.label, row.value));
  }
  panel.append(metrics);
  return panel;
}

function createSectionHeader(title, countLabel) {
  const header = createNode("header", "section-header");
  header.append(createNode("h2", "", title), createNode("span", "pill", countLabel));
  return header;
}

function formatList(items, emptyLabel) {
  if (!items?.length) {
    return createNode("div", "empty", emptyLabel);
  }

  const list = createNode("ul", "finding-list");
  for (const item of items) {
    const entry = createNode("li", "finding");
    entry.append(createNode("strong", "", item.title), createNode("p", "", item.description));
    list.append(entry);
  }
  return list;
}

function renderFindings(title, findings) {
  const panel = createNode("section", "panel scheme");
  panel.append(createSectionHeader(title, `${findings.length} items`));

  if (!findings.length) {
    panel.append(createNode("div", "empty", "No findings in the top-N slice for this scheme."));
    return panel;
  }

  const list = createNode("ul", "finding-list");
  for (const finding of findings) {
    const item = createNode("li", "finding");
    const reasons = finding.reasons?.length ? finding.reasons.join(" ") : "No textual explanation recorded.";
    const metrics = finding.metrics || {};

    item.append(
      createNode("strong", "", `${finding.entity_id} · score ${finding.score}`),
      createNode(
        "p",
        "",
        `claims: ${metrics.claim_count ?? "n/a"} · avg amount: ${metrics.average_amount ?? metrics.total_amount ?? "n/a"} · note: ${reasons}`,
      ),
    );
    list.append(item);
  }

  panel.append(list);
  return panel;
}

function renderLinkList(title, links, emptyLabel, mapper) {
  const panel = createNode("section", "panel network-panel");
  panel.append(createSectionHeader(title, `${links.length} links`));

  if (!links.length) {
    panel.append(createNode("div", "empty", emptyLabel));
    return panel;
  }

  const list = createNode("ul", "finding-list");
  for (const link of links.slice(0, 5)) {
    const item = createNode("li", "finding link-finding");
    item.append(createNode("strong", "", mapper.title(link)), createNode("p", "", mapper.description(link)));
    list.append(item);
  }

  panel.append(list);
  return panel;
}

function renderReport(report) {
  app.innerHTML = "";

  const hero = createNode("section", "hero fade-in");
  hero.append(
    createNode("p", "eyebrow", "ClaimGuard Network"),
    createNode("h1", "", "Network risk, surfaced."),
    createNode(
      "p",
      "lede",
      "This dashboard reads the synthetic detection report generated by the Phase 4 engine and highlights suspicious providers, members, and scheme-level summary metrics.",
    ),
  );

  const schemes = report?.schemes || [];
  const firstScheme = schemes[0];
  const statusRow = createNode("div", "status-row");
  statusRow.append(
    createNode("span", "pill", `Schemes: ${schemes.length}`),
    createNode("span", "pill", `Data dir: ${report?.data_dir || "unknown"}`),
    createNode("span", "pill", firstScheme ? `Current: ${firstScheme.scheme_id}` : "No scheme data"),
  );
  hero.append(statusRow);

  const grid = createNode("section", "grid fade-in");
  const summaryPanel = createNode("section", "panel");
  summaryPanel.append(createSectionHeader("Summary", `${schemes.length} schemes`));

  if (firstScheme) {
    const metrics = createNode("div", "metrics");
    metrics.append(
      createMetric("Providers", firstScheme.provider_count ?? 0),
      createMetric("Claims", firstScheme.claim_count ?? 0),
      createMetric("Members", firstScheme.member_count ?? 0),
      createMetric("Member same-day peak", firstScheme.summary?.member_same_day_provider_peak ?? 0),
    );
    summaryPanel.append(metrics);
  } else {
    summaryPanel.append(createNode("div", "empty", "No scheme data returned by the API proxy."));
  }

  grid.append(summaryPanel);

  for (const scheme of schemes) {
    const schemePanel = createNode("section", "panel scheme");
    const header = createNode("header");
    header.append(
      createNode("div", "", scheme.scheme_id),
      createNode("span", "pill", `providers ${scheme.provider_count} · claims ${scheme.claim_count}`),
    );
    schemePanel.append(header);

    const miniMetrics = createNode("div", "metrics");
    miniMetrics.append(
      createMetric("Provider median", scheme.summary?.provider_average_amount_median ?? 0),
      createMetric("Claim-rate median", scheme.summary?.provider_claim_rate_median ?? 0),
      createMetric("Member claim median", scheme.summary?.member_claim_count_median ?? 0),
      createMetric("Same-day peak", scheme.summary?.member_same_day_provider_peak ?? 0),
    );

    schemePanel.append(miniMetrics);
    schemePanel.append(renderFindings("Provider findings", scheme.provider_findings || []));
    schemePanel.append(renderFindings("Member findings", scheme.member_findings || []));
    grid.append(schemePanel);
  }

  if (report?.network) {
    const network = report.network;
    const exactLinks = network.exact_banking_links || [];
    const behavioralLinks = network.behavioral_provider_links || [];
    const resolvedEntities = network.resolved_entities || [];

    grid.append(
      createKeyValuePanel("Network Summary", [
        { label: "Exact bank links", value: exactLinks.length },
        { label: "Behavioral links", value: behavioralLinks.length },
        { label: "Resolved entities", value: resolvedEntities.length },
        { label: "Provider nodes", value: (network.network_nodes || []).length },
      ]),
    );

    grid.append(
      renderLinkList(
        "Exact banking links",
        exactLinks,
        "No cross-scheme bank matches detected in the current slice.",
        {
          title: (link) => `${link.bank_key} · ${link.providers.length} providers`,
          description: (link) => `${link.providers.map((provider) => provider.provider_id).join(" ↔ ")} · schemes ${link.providers.map((provider) => provider.scheme_id).join(", ")}`,
        },
      ),
    );

    grid.append(
      renderLinkList(
        "Behavioral provider links",
        behavioralLinks,
        "No fuzzy provider relationships crossed the confidence threshold.",
        {
          title: (link) => `${link.providers.join(" ↔ ")} · confidence ${link.confidence}`,
          description: (link) => `${link.reason || "behavioral similarity link"} · signatures ${link.signature_similarity ?? "n/a"}`,
        },
      ),
    );

    const resolvedPanel = createNode("section", "panel");
    resolvedPanel.append(createSectionHeader("Resolved Provider Clusters", `${resolvedEntities.length} clusters`));
    resolvedPanel.append(
      formatList(
        resolvedEntities.slice(0, 3).map((entity) => ({
          title: `${entity.resolved_entity_id} · confidence ${entity.confidence}`,
          description: `${entity.schemes.join(", ")} · ${entity.providers.join(", ")}`,
        })),
        "No cross-scheme clusters detected in the current slice.",
      ),
    );
    grid.append(resolvedPanel);
  }

  if (report?.evaluation) {
    const evaluation = report.evaluation;
    grid.append(
      createKeyValuePanel("Evaluation", [
        { label: "Single-scheme recall", value: evaluation.single_scheme?.recall ?? "n/a" },
        { label: "Cross-scheme recall", value: evaluation.cross_scheme?.recall ?? "n/a" },
        { label: "Single detected", value: evaluation.single_scheme?.detected ?? 0 },
        { label: "Cross detected", value: evaluation.cross_scheme?.detected ?? 0 },
      ]),
    );

    if (evaluation.available === false) {
      grid.append(createNode("section", "panel", "Ground-truth evaluation data is not available for the current slice."));
    }
  }

  const buttonPanel = createNode("section", "panel");
  const button = createNode("button", "", "Throw Test Error");
  button.type = "button";
  button.addEventListener("click", async () => {
    const error = new Error("Phase0 web Sentry smoke test error");
    Sentry.captureException(error);
    await Sentry.flush(2000);
    window.alert("Captured web Sentry smoke test error and flushed the event.");
  });
  buttonPanel.append(createNode("h2", "", "Smoke test"), createNode("p", "lede", "Use this to confirm browser telemetry is still wired."), button);

  app.append(hero, grid, buttonPanel);
}

async function loadReport() {
  renderLoading();

  try {
    const response = await fetch("/api/detection/report");
    const payload = await response.json();

    if (!response.ok || !payload.available) {
      renderError(payload.message || `Detection report unavailable (${response.status})`);
      return;
    }

    renderReport(payload.report);
  } catch (error) {
    renderError(error instanceof Error ? error.message : "Failed to load detection report.");
  }
}

if (app) {
  loadReport();
}