"""
Generates docs/data_dictionary.md as part of the pipeline output (spec §3
deliverable #4: "a short data dictionary... exported alongside the data").
"""
from __future__ import annotations

from pathlib import Path

DATA_DICTIONARY_MD = """# ClaimGuard Network — Phase 1 Data Dictionary

Generated by the Phase 1 synthetic data generator. Matches
`ClaimGuard_Phase1_Data_Generator_Spec.md` §5, with two small, clearly-flagged
extensions noted below.

## Scheme

| Field | Type | Notes |
|---|---|---|
| scheme_id | string | `"A"`, `"B"`, `"C"` |
| scheme_name | string | e.g. "Scheme A Medical Fund" |

## Member (`members.csv`)

| Field | Type | Notes |
|---|---|---|
| member_id | string | scheme-local, e.g. `A-M00001` |
| scheme_id | string | |
| first_name, last_name | string | synthetic (Faker, zu_ZA locale) |
| date_of_birth | date (ISO 8601) | drives age-band claim frequency and age-restricted billing codes |
| **gender** | string, `F`/`M` | **Extension beyond the spec's literal schema.** Not in §5's Member table. Added because it's needed for gender-appropriate name generation and for the age/gender-inconsistent variant of membership substitution (§7); kept as an explicit column rather than inferred from ID-number digits. Drop it if you'd rather match §5 exactly. |
| synthetic_id_number | string | 13 digits, South-African-ID-*shaped* (DOB-prefixed, Luhn check digit). **Fully synthetic** — not a real ID-number algorithm output and not linked to any real person. Never treat it as a validity check for real IDs. |
| synthetic_banking_detail | string | `"{bank_name}\\|{account_number}"` |
| home_region, home_lat, home_lon | string, float, float | member's home location — spec's `home_location` split into 3 columns |
| join_date | date (ISO 8601) | when they joined this scheme; claims never precede this |

## Provider (`providers.csv`)

| Field | Type | Notes |
|---|---|---|
| provider_id | string | scheme-local, e.g. `A-P0001`. Providers that reappear after cross-scheme evasion (§8) get a fresh, sequentially-continued ID in their new scheme. |
| scheme_id | string | |
| practice_number | string | synthetic, scheme-local |
| specialty | categorical | GP, Dentist, Physiotherapist, Specialist, Pharmacy, Optometrist, Psychologist |
| **practice_name** | string | **Extension beyond the spec's literal schema.** §5's Provider table has no name field at all, but §8's evasion mechanic explicitly requires "a different name" as part of the disguise — so a name field has to exist somewhere for that sentence to be implementable. Added as a practice/business name (e.g. "Naidoo Family Practice") rather than a personal name, since providers aren't given first/last name fields. |
| synthetic_banking_detail | string | same format as Member's. This is the field cross-scheme evasion (§8) deliberately reuses unchanged. |
| practice_region, practice_lat, practice_lon | string, float, float | spec's `practice_location` split into 3 columns |

Not exported (internal generation parameters only, used to drive claims.csv and not part of the spec's schema): each provider's individual billing-code fingerprint, severity (average claim amount) parameter, and capacity weight.

## Claim (`claims.csv`)

| Field | Type | Notes |
|---|---|---|
| claim_id | string | globally unique across all 3 schemes |
| scheme_id | string | |
| member_id | string | references Member |
| provider_id | string | references Provider |
| service_date | date (ISO 8601) | within the 24-month window |
| billing_code | categorical | one per claim (v1 — no multi-line claims) |
| amount | float | in ZAR (illustrative, hand-set log-normal parameters per specialty — no real claims data was fitted, per spec §2/§12) |

## Ground truth (`ground_truth/planted_fraud.json`)

Structure matches spec §9 exactly: `single_scheme_fraud`, `collusion_rings`,
`cross_scheme_evasion`. Each record carries enough detail (peer stats used,
spike days injected, distances computed, attributes preserved/changed) to
audit *why* it was flagged, not just that it was.

## Fraud archetypes planted (spec §7-§8)

| Archetype | Count (per scheme unless noted) | Where |
|---|---|---|
| Up-coding provider | 6 | `single_scheme_fraud`, archetype `up_coding` |
| Membership substitution (geographic) | 8 | `single_scheme_fraud`, archetype `membership_substitution`, variant `geographic` |
| Membership substitution (demographic) | 4 | `single_scheme_fraud`, archetype `membership_substitution`, variant `demographic` |
| Provider-member collusion ring | 2 rings x 6 members | `collusion_rings` |
| Ghost / high-volume claiming | 3 | `single_scheme_fraud`, archetype `ghost_claiming` |
| Cross-scheme evasion | 5 total (from Scheme A only) | `cross_scheme_evasion` |

## Known extensions beyond the literal spec schema

1. `Member.gender` — see note above.
2. `Provider.practice_name` — see note above.

Both are additive (no spec-listed field was removed or renamed) and are
called out here, in the code's module docstrings, and in the build summary
so they're easy to drop if you want the schema to match §5 byte-for-byte.
"""


def write_data_dictionary(path: str | Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(DATA_DICTIONARY_MD)
