export const CANONICAL_OPERATIONAL_SCHEMA_VERSION = "18";

export const CANONICAL_OPERATIONAL_MIGRATION_VERSION =
  Number(CANONICAL_OPERATIONAL_SCHEMA_VERSION);

export const CANONICAL_OPERATIONAL_MIGRATION_ID =
  "0018_versioned_assessment_context";

export const CANONICAL_OPERATIONAL_SCHEMA_VERSIONS =
  Object.freeze([
    CANONICAL_OPERATIONAL_SCHEMA_VERSION,
  ]);
