export const CANONICAL_OPERATIONAL_SCHEMA_VERSION = "15";

export const CANONICAL_OPERATIONAL_MIGRATION_VERSION =
  Number(CANONICAL_OPERATIONAL_SCHEMA_VERSION);

export const CANONICAL_OPERATIONAL_MIGRATION_ID =
  "0015_investigation_workflow";

export const CANONICAL_OPERATIONAL_SCHEMA_VERSIONS =
  Object.freeze([
    CANONICAL_OPERATIONAL_SCHEMA_VERSION,
  ]);