export const CANONICAL_OPERATIONAL_SCHEMA_VERSION = "17";

export const CANONICAL_OPERATIONAL_MIGRATION_VERSION =
  Number(CANONICAL_OPERATIONAL_SCHEMA_VERSION);

export const CANONICAL_OPERATIONAL_MIGRATION_ID =
  "0017_case_state_machine";

export const CANONICAL_OPERATIONAL_SCHEMA_VERSIONS =
  Object.freeze([
    CANONICAL_OPERATIONAL_SCHEMA_VERSION,
  ]);
