import "./mysql-core.integration.test.js";
import "./assessment-correction-mysql.integration.test.js";
import "./assessment-reassessment-mysql.integration.test.js";
import "./case-workflow-mysql.integration.test.js";
import "./case-workflow-rollback-mysql.integration.test.js";
import "./legacy-first-access-matrix-mysql.integration.test.js";
import "./legacy-first-access-concurrency-mysql.integration.test.js";
import "./legacy-first-access-rollback-mysql.integration.test.js";
import "./legacy-first-access-negative-mysql.integration.test.js";
